# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(choices=[('admin@trumpispoopy.com', 'admin@trumpispoopy.com'), ('albertocamoo@gmail.com', 'albertocamoo@gmail.com'), ('a.lbertocamoo@gmail.com', 'a.lbertocamoo@gmail.com'), ('al.bertocamoo@gmail.com', 'al.bertocamoo@gmail.com'), ('alb.ertocamoo@gmail.com', 'alb.ertocamoo@gmail.com'), ('albe.rtocamoo@gmail.com', 'albe.rtocamoo@gmail.com'), ('alber.tocamoo@gmail.com', 'alber.tocamoo@gmail.com'), ('albert.ocamoo@gmail.com', 'albert.ocamoo@gmail.com'), ('alberto.camoo@gmail.com', 'alberto.camoo@gmail.com'), ('albertoc.amoo@gmail.com', 'albertoc.amoo@gmail.com'), ('albertoca.moo@gmail.com', 'albertoca.moo@gmail.com'), ('albertocam.oo@gmail.com', 'albertocam.oo@gmail.com'), ('albertocamo.o@gmail.com', 'albertocamo.o@gmail.com'), ('ernestmichealhemingway@gmail.com', 'ernestmichealhemingway@gmail.com'), ('e.rnestmichealhemingway@gmail.com', 'e.rnestmichealhemingway@gmail.com'), ('er.nestmichealhemingway@gmail.com', 'er.nestmichealhemingway@gmail.com'), ('ern.estmichealhemingway@gmail.com', 'ern.estmichealhemingway@gmail.com'), ('erne.stmichealhemingway@gmail.com', 'erne.stmichealhemingway@gmail.com'), ('ernes.tmichealhemingway@gmail.com', 'ernes.tmichealhemingway@gmail.com'), ('ernest.michealhemingway@gmail.com', 'ernest.michealhemingway@gmail.com')], max_length=254, unique=True)),
                ('handle', models.CharField(max_length=32)),
                ('token', models.CharField(blank=True, max_length=64, null=True)),
                ('secret', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(max_length=64)),
                ('text', models.TextField(blank=True, null=True)),
                ('text_model', models.TextField(blank=True, editable=False, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='media/avatar')),
                ('interests', models.CharField(blank=True, max_length=256, null=True)),
                ('follower_list', models.ManyToManyField(blank=True, related_name='follower', to='authors.Author')),
                ('following_list', models.ManyToManyField(blank=True, related_name='following', to='authors.Author')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.Author')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=32)),
                ('twitter_id', models.BigIntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='twitteruser',
            unique_together=set([('handle', 'twitter_id')]),
        ),
        migrations.AddField(
            model_name='author',
            name='randomly_following',
            field=models.ManyToManyField(blank=True, editable=False, to='authors.TwitterUser'),
        ),
        migrations.AlterUniqueTogether(
            name='previoustweet',
            unique_together=set([('author', 'text')]),
        ),
    ]
