from django.db import models
from django.conf import settings
import twitter
import markovify
import pprint
import random

POSSIBLE_EMAILS = [
    'admin@trumpispoopy.com',
    'albertocamoo@gmail.com',
    'a.lbertocamoo@gmail.com',
    'al.bertocamoo@gmail.com',
    'alb.ertocamoo@gmail.com',
    'albe.rtocamoo@gmail.com',
    'alber.tocamoo@gmail.com',
    'albert.ocamoo@gmail.com',
    'alberto.camoo@gmail.com',
    'albertoc.amoo@gmail.com',
    'albertoca.moo@gmail.com',
    'albertocam.oo@gmail.com',
    'albertocamo.o@gmail.com',
    'ernestmichealhemingway@gmail.com',
    'e.rnestmichealhemingway@gmail.com',
    'er.nestmichealhemingway@gmail.com',
    'ern.estmichealhemingway@gmail.com',
    'erne.stmichealhemingway@gmail.com',

    'ernes.tmichealhemingway@gmail.com',
    'ernest.michealhemingway@gmail.com',

]

#   WM4xr4kLgQUffDhrjXxtP8gZ
#   (612) 460-1290

INSULTS = [
    "you ridiculous bloviating asshole",
    "you gibbering shitweasel",
    "you cream-faced babbling fool",
    "you obnoxious festering canker",
    "you asinine ragemonger",
    "you moronic lying shitgoblin",
    "you idiotic cantankerous toad",
    "you wiggy slice",
    "you uncooked pastry",
    "you Spoon",
    "you few fries short of a Happy Meal",
    "you moron, you stupid moron, fucking moron, you biggest fucking moron on the planet right now",
    "you dickhead",
    "you twat",
    "You're a boob, tit",
    "you fucking Bonehead",
    "you pee soaked tiny hands",
    "you pumpkinfart",
    "you absolute glove puppet",
    "you Mangled apricot hellbeast",
    "you muppet",
    "you Twatwaffle",
    "You braindead quisling",
    "you giant fucking ball sack.",
    "ya fucking ejit",
    "you numpty, total and utter numpty",
    "you Narcissistic egotistical buffoon.",
    "ye daft bawbag. Arse from elbow!",
    "you utter Twonk",
    "you twat-faced asshat",
    "you idiotic delusional psychopathic compulsive liar",
    "you ludicrous tangerine ballsack",
    "you Bloviating flesh bag",
    "you weapons-grade plum",
    "you polyester cockwomble",
    "you really are a cockwomble",
    "You complete bumblecunt",
    "you rag-haired, cunty, twat-badger!!",
    "you Geehonk.",
    "you Fuckstick Helmethair",
    "you Weaselheaded fucknugget",
    "you Incrompressible Jizztrumpet",
    "you leather faced, shit-tobogganist",
    "you toupéd fucktrumpet",
    "you tiny fingered, Cheeto-faced, ferret wearing shitgibbon.",
    "YOU WITLESS FUCKING COCKSPLAT!",
    "you Oi, buttplug face!",
]



EMOJI = [

    ('😄','A_smiley1'),
    ('😃','A_smiley2'),
    ('😀','A_smiley3'),
    ('😊','A_smiley4'),
    ('😉','A_wink'),
    ('😍','A_loveeyes'),
    ('😘','A_kiss1 '),
    ('😚','A_kiss2'),
    ('😗','A_kiss3'),
    ('😙','A_kiss4'),
    ('😜','A_tongue1'),
    ('😝','A_tongue2'),
    ('😛','A_tongue3'),
    ('😳','A_embarassed'),
    ('😁','A_cheese'),
    ('😔','A_sad1'),
    ('😌','A_sad2'),
    ('😒','A_sad3'),
    ('😞','A_sad4'),
    ('😣','A_sad5'),
    ('😢','A_sad6'),
    ('😂','A_sad7'),
    ('😭','A_sad8'),
    ('😪','A_sad9'),
    ('😥','A_sad10'),
    ('😰','A_sad11'),
    ('😅','A_sad12'),
    ('😓','A_sad13'),
    ('😩','A_sad14'),
    ('😫','A_sad15'),
    ('😨','A_worry1'),
    ('😱','A_worry2'),
    ('😠','A_angry1'),
    ('😡','A_angry2'),
    ('😤','A_angry3'),
    ('😖','A_wince'),
    ('😆','A_laugh'),
    ('😋','A_licklips'),
    ('😷','A_respirator'),
    ('😎','A_sunglasses'),
    ('😴','A_Zzz'),
    ('😵','A_dead1'),
    ('😲','A_dead2'),
    ('😟','A_worry1'),
    ('😦','A_worry2'),
    ('😧','A_worry3'),
    ('😈','A_devil1'),
    ('👿','A_devil2'),
    ('😮','A_oh'),
    ('😬','A_cheese2'),
    ('😐','A_straight'),
    ('😕','A_worry4'),
    ('😯','A_oh2'),
    ('😶','A_nomouth'),
    ('😇','A_angel'),
    ('😏','A_smirk'),
    ('😑','A_straight2'),
    ('👲','B_gua'),
    ('👲🏻','B_gua1'),
    ('👲🏼','B_gua2'),
    ('👲🏽','B_gua3'),
    ('👲🏾','B_gua4'),
    ('👲🏿','B_gua5'),
    ('👳','B_turbin'),
    ('👳🏻','B_turbin1'),
    ('👳🏼','B_turbin2'),
    ('👳🏽','B_turbin3'),
    ('👳🏾','B_turbin4'),
    ('👳🏿','B_turbin5'),
    ('👮','B_police'),
    ('👮🏻','B_police1'),
    ('👮🏼','B_police2'),
    ('👮🏽','B_police3'),
    ('👮🏾','B_police4'),
    ('👮🏿','B_police5'),
    ('👷','B_safety'),
    ('👷🏻','B_safety1'),
    ('👷🏼','B_safety2'),
    ('👷🏽','B_safety3'),
    ('👷🏾','B_safety4'),
    ('👷🏿','B_safety5'),
    ('💂','B_russian'),
    ('💂🏻','B_russian1'),
    ('💂🏼','B_russian2'),
    ('💂🏽','B_russian3'),
    ('💂🏾','B_russian4'),
    ('💂🏿','B_russian5'),
    ('👶','B_baby'),
    ('👶🏻','B_baby1'),
    ('👶🏼','B_baby2'),
    ('👶🏽','B_baby3'),
    ('👶🏾','B_baby4'),
    ('👶🏿','B_baby5'),
    ('👦','B_boy'),
    ('👦🏻','B_boy1'),
    ('👦🏼','B_boy2'),
    ('👦🏽','B_boy3'),
    ('👦🏾','B_boy4'),
    ('👦🏿','B_boy5'),
    ('👧','B_girl'),
    ('👧🏻','B_girl1'),
    ('👧🏼','B_girl2'),
    ('👧🏽','B_girl3'),
    ('👧🏾','B_girl4'),
    ('👧🏿','B_girl5'),
    ('👨','B_man'),
    ('👨🏻','B_man1'),
    ('👨🏼','B_man2'),
    ('👨🏽','B_man3'),
    ('👨🏾','B_man4'),
    ('👨🏿','B_man5'),
    ('👩','B_woman'),
    ('👩🏻','B_woman1'),
    ('👩🏼','B_woman2'),
    ('👩🏽','B_woman3'),
    ('👩🏾','B_woman4'),
    ('👩🏿','B_woman5'),
    ('👴','B_grandpa'),
    ('👴🏻','B_grandpa1'),
    ('👴🏼','B_grandpa2'),
    ('👴🏽','B_grandpa3'),
    ('👴🏾','B_grandpa4'),
    ('👴🏿','B_grandpa5'),
    ('👵','B_grandma'),
    ('👵🏻','B_grandma1'),
    ('👵🏼','B_grandma2'),
    ('👵🏽','B_grandma3'),
    ('👵🏾','B_grandma4'),
    ('👵🏿','B_grandma5'),
    ('👱','B_blonde'),
    ('👱🏻','B_blonde1'),
    ('👱🏼','B_blonde2'),
    ('👱🏽','B_blonde3'),
    ('👱🏾','B_blonde4'),
    ('👱🏿','B_blonde5'),
    ('👼','B_angel'),
    ('👼🏻','B_angel1'),
    ('👼🏼','B_angel2'),
    ('👼🏽','B_angel3'),
    ('👼🏾','B_angel4'),
    ('👼🏿','B_angel5'),
    ('👸','B_princess'),
    ('👸🏻','B_princess1'),
    ('👸🏼','B_princess2'),
    ('👸🏽','B_princess3'),
    ('👸🏾','B_princess4'),
    ('👸🏿','B_princess5'),
    ('😺','C_smile1'),
    ('😸','C_smile2'),
    ('😻','C_hearteyes'),
    ('😽','C_kiss'),
    ('😼','C_angry'),
    ('🙀','C_shocked'),
    ('😿','C_sad1'),
    ('😹','C_sad2'),
    ('😾','C_side1'),
    ('👹','C_redmask'),
    ('👺','C_redmask2'),
    ('🙈','C_seeno'),
    ('🙉','C_hearno'),
    ('🙊','C_speakno'),
    ('💀','C_skull'),
    ('👽','C_alien'),
    ('💩','D_poop'),
    ('🔥','D_fire'),
    ('✨','D_stars1'),
    ('🌟','D_stars2'),
    ('💫','D_stars3'),
    ('💥','D_firework'),
    ('💢','D_flare'),
    ('💦','D_water1'),
    ('💧','D_water2'),
    ('💤','D_Zzz'),
    ('💨','D_wind'),
    ('👂','D_ear'),
    ('👂🏻','D_ear1'),
    ('👂🏼','D_ear2'),
    ('👂🏽','D_ear3'),
    ('👂🏾','D_ear4'),
    ('👂🏿','D_ear5'),
    ('👀','D_eyes'),
    ('👃','D_nose'),
    ('👃🏻','D_nose1'),
    ('👃🏼','D_nose2'),
    ('👃🏽','D_nose3'),
    ('👃🏾','D_nose4'),
    ('👃🏿','D_nose5'),
    ('👅','D_tongue'),
    ('👄','D_lips'),
    ('👍','D_thumbsup'),
    ('👍🏻','D_thumbsup1'),
    ('👍🏼','D_thumbsup2'),
    ('👍🏽','D_thumbsup3'),
    ('👍🏾','D_thumbsup4'),
    ('👍🏿','D_thumbsup5'),
    ('👎','D_thumbsdown'),
    ('👎🏻','D_thumbsdown1'),
    ('👎🏼','D_thumbsdown2'),
    ('👎🏽','D_thumbsdown3'),
    ('👎🏾','D_thumbsdown4'),
    ('👎🏿','D_thumbsdown5'),
    ('👌','D_ok'),
    ('👌🏻','D_ok1'),
    ('👌🏼','D_ok2'),
    ('👌🏽','D_ok3'),
    ('👌🏾','D_ok4'),
    ('👌🏿','D_ok5'),
    ('👊','D_pound'),
    ('👊🏻','D_pound1'),
    ('👊🏼','D_pound2'),
    ('👊🏽','D_pound3'),
    ('👊🏾','D_pound4'),
    ('👊🏿','D_pound5'),
    ('✊','D_power'),
    ('✊🏻','D_power1'),
    ('✊🏼','D_power2'),
    ('✊🏽','D_power3'),
    ('✊🏾','D_power4'),
    ('✊🏿','D_power5'),
    ('✌️','D_victory'),
    ('✌🏻','D_victory1'),
    ('✌🏼','D_victory2'),
    ('✌🏽','D_victory3'),
    ('✌🏾','D_victory4'),
    ('✌🏿','D_victory5'),
    ('👋','D_wave'),
    ('👋🏻','D_wave1'),
    ('👋🏼','D_wave2'),
    ('👋🏽','D_wave3'),
    ('👋🏾','D_wave4'),
    ('👋🏿','D_wave5'),
    ('✋','D_raise'),
    ('✋🏻','D_raise1'),
    ('✋🏼','D_raise2'),
    ('✋🏽','D_raise3'),
    ('✋🏾','D_raise4'),
    ('✋🏿','D_raise5'),
    ('👐','D_W'),
    ('👐🏻','D_W1'),
    ('👐🏼','D_W2'),
    ('👐🏽','D_W3'),
    ('👐🏾','D_W4'),
    ('👐🏿','D_W5'),
    ('👆','D_pointup'),
    ('👆🏻','D_pointup1'),
    ('👆🏼','D_pointup2'),
    ('👆🏽','D_pointup3'),
    ('👆🏾','D_pointup4'),
    ('👆🏿','D_pointup5'),
    ('👇','D_pointdown'),
    ('👇🏻','D_pointdown1'),
    ('👇🏼','D_pointdown2'),
    ('👇🏽','D_pointdown3'),
    ('👇🏾','D_pointdown4'),
    ('👇🏿','D_pointdown5'),
    ('👉','D_pointright'),
    ('👉🏻','D_pointright1'),
    ('👉🏼','D_pointright2'),
    ('👉🏽','D_pointright3'),
    ('👉🏾','D_pointright4'),
    ('👉🏿','D_pointright5'),
    ('👈','D_pointleft'),
    ('👈🏻','D_pointleft1'),
    ('👈🏼','D_pointleft2'),
    ('👈🏽','D_pointleft3'),
    ('👈🏾','D_pointleft4'),
    ('👈🏿','D_pointleft5'),
    ('🙌','D_td'),
    ('🙌🏻','D_td1'),
    ('🙌🏼','D_td2'),
    ('🙌🏽','D_td3'),
    ('🙌🏾','D_td4'),
    ('🙌🏿','D_td5'),
    ('🙏','D_prayer'),
    ('🙏🏻','D_prayer1'),
    ('🙏🏼','D_prayer2'),
    ('🙏🏽','D_prayer3'),
    ('🙏🏾','D_prayer4'),
    ('🙏🏿','D_prayer5'),
    ('☝️','D_number'),
    ('☝🏻','D_number1'),
    ('☝🏼','D_number2'),
    ('☝🏽','D_number3'),
    ('☝🏾','D_number4'),
    ('☝🏿','D_number5'),
    ('👏','D_clap'),
    ('👏🏻','D_clap1'),
    ('👏🏼','D_clap2'),
    ('👏🏽','D_clap3'),
    ('👏🏾','D_clap4'),
    ('👏🏿','D_clap5'),
    ('💪','D_bicep'),
    ('💪🏻','D_bicep1'),
    ('💪🏼','D_bicep2'),
    ('💪🏽','D_bicep3'),
    ('💪🏾','D_bicep4'),
    ('💪🏿','D_bicep5'),
    ('🚶','E_walk'),
    ('🚶🏻','E_walk1'),
    ('🚶🏼','E_walk2'),
    ('🚶🏽','E_walk3'),
    ('🚶🏾','E_walk4'),
    ('🚶🏿','E_walk5'),
    ('🏃','E_run'),
    ('🏃🏻','E_run1'),
    ('🏃🏼','E_run2'),
    ('🏃🏽','E_run3'),
    ('🏃🏾','E_run4'),
    ('🏃🏿','E_run5'),
    ('💃','E_salsa'),
    ('💃🏻','E_salsa1'),
    ('💃🏼','E_salsa2'),
    ('💃🏽','E_salsa3'),
    ('💃🏾','E_salsa4'),
    ('💃🏿','E_salsa5'),
    ('👫','E_couple'),
    ('👪','E_family'),
    ('👨‍👩‍👧','E_family1'),
    ('👨‍👩‍👧‍👦','E_family2'),
    ('👨‍👩‍👦‍👦','E_family3'),
    ('👨‍👩‍👧‍👧','E_family4'),
    ('👩‍👩‍👦','E_family5'),
    ('👩‍👩‍👧','E_family6'),
    ('👩‍👩‍👧‍👦','E_family7'),
    ('👩‍👩‍👦‍👦','E_family8'),
    ('👩‍👩‍👧‍👧','E_family9'),
    ('👨‍👨‍👦','E_family10'),
    ('👨‍👨‍👧','E_family11'),
    ('👨‍👨‍👧‍👦','E_family12'),
    ('👨‍👨‍👦‍👦','E_family13'),
    ('👨‍👨‍👧‍👧','E_family14'),
    ('👬','E_men'),
    ('👭','E_women'),
    ('💏','E_coupleheart'),
    ('💑','E_coupleheart2'),
    ('👯','E_dancers'),
    ('🙆','E_O'),
    ('🙆🏻','E_O1'),
    ('🙆🏼','E_O2'),
    ('🙆🏽','E_O3'),
    ('🙆🏾','E_O4'),
    ('🙆🏿','E_O5'),
    ('🙅','E_X'),
    ('🙅🏻','E_X1'),
    ('🙅🏼','E_X2'),
    ('🙅🏽','E_X3'),
    ('🙅🏾','E_X4'),
    ('🙅🏿','E_X5'),
    ('💁','E_Chrissy'),
    ('💁🏻','E_Chrissy1'),
    ('💁🏼','E_Chrissy2'),
    ('💁🏽','E_Chrissy3'),
    ('💁🏾','E_Chrissy4'),
    ('💁🏿','E_Chrissy5'),
    ('🙋','E_handraise'),
    ('🙋🏻','E_handraise1'),
    ('🙋🏼','E_handraise2'),
    ('🙋🏽','E_handraise3'),
    ('🙋🏾','E_handraise4'),
    ('🙋🏿','E_handraise5'),
    ('💆','E_washhair'),
    ('💆🏻','E_washhair1'),
    ('💆🏼','E_washhair2'),
    ('💆🏽','E_washhair3'),
    ('💆🏾','E_washhair4'),
    ('💆🏿','E_washhair5'),
    ('💇','E_cuthair'),
    ('💇🏻','E_cuthair1'),
    ('💇🏼','E_cuthair2'),
    ('💇🏽','E_cuthair3'),
    ('💇🏾','E_cuthair4'),
    ('💇🏿','E_cuthair5'),
    ('💅','E_nails'),
    ('💅🏻','E_nails1'),
    ('💅🏼','E_nails2'),
    ('💅🏽','E_nails3'),
    ('💅🏾','E_nails4'),
    ('💅🏿','E_nails5'),
    ('👰','E_bride'),
    ('👰🏻','E_bride1'),
    ('👰🏼','E_bride2'),
    ('👰🏽','E_bride3'),
    ('👰🏾','E_bride4'),
    ('👰🏿','E_bride5'),
    ('🙎','E_whistle'),
    ('🙎🏻','E_whistle1'),
    ('🙎🏼','E_whistle2'),
    ('🙎🏽','E_whistle3'),
    ('🙎🏾','E_whistle4'),
    ('🙎🏿','E_whistle5'),
    ('🙍','E_sad'),
    ('🙍🏻','E_sad1'),
    ('🙍🏼','E_sad2'),
    ('🙍🏽','E_sad3'),
    ('🙍🏾','E_sad4'),
    ('🙍🏿','E_sad5'),
    ('🙇','E_headdown'),
    ('🙇🏻','E_headdown1'),
    ('🙇🏼','E_headdown2'),
    ('🙇🏽','E_headdown3'),
    ('🙇🏾','E_headdown4'),
    ('🙇🏿','E_headdown5'),
    ('🎩','F_tophat'),
    ('👑','F_crown'),
    ('👒','F_derbyhat'),
    ('👟','F_whiteshoe'),
    ('👞','F_brownshoe'),
    ('👡','F_slipon'),
    ('👠','F_heel'),
    ('👢','F_boot'),
    ('👕','F_polo'),
    ('👔','F_shirttie'),
    ('👚','F_blouse'),
    ('👗','F_dress'),
    ('🎽','F_workout'),
    ('👖','F_jeans'),
    ('👘','F_asian'),
    ('👙','F_bikini'),
    ('💼','F_brief'),
    ('👜','F_bag1'),
    ('👝','F_bag2'),
    ('👛','F_bag3'),
    ('👓','F_glasses'),
    ('🎀','F_bow'),
    ('🌂','F_umbrella'),
    ('💄','F_lipstick'),
    ('💛','F_yellowheart'),
    ('💙','F_blueheart'),
    ('💜','F_purpleheart'),
    ('💚','F_greenheart'),
    ('❤️','F_redheart'),
    ('💔','F_brokenheart'),
    ('💗','F_growingheart'),
    ('💓','F_ringingheart'),
    ('💕','F_twohearts'),
    ('💖','F_sparkleheart'),
    ('💞','F_revolvingheart'),
    ('💘','F_cupidheart'),
    ('💌','F_letterheart'),
    ('💋','F_lips'),
    ('💍','F_ring'),
    ('💎','F_diamond'),
    ('👤','F_user'),
    ('👥','F_user2'),
    ('💬','F_message'),
    ('👣','F_footprint'),
    ('💭','F_thought'),
    ('🐶','G_dog'),
    ('🐺','G_fox'),
    ('🐱','G_cat'),
    ('🐭','G_mouse1'),
    ('🐹','G_mouse2'),
    ('🐰','G_rabbit'),
    ('🐸','G_frog'),
    ('🐯','G_tiger'),
    ('🐨','G_koala'),
    ('🐻','G_bear'),
    ('🐷','G_pig1'),
    ('🐽','G_pig2'),
    ('🐮','G_cow'),
    ('🐗','G_warthog'),
    ('🐵','G_monkey1'),
    ('🐒','G_monkey2'),
    ('🐴','G_horse'),
    ('🐑','G_sheep'),
    ('🐘','G_elephant'),
    ('🐼','G_panda'),
    ('🐧','G_penguin1'),
    ('🐦','G_penguin2'),
    ('🐤','G_chick1'),
    ('🐥','G_chick2'),
    ('🐣','G_chick2'),
    ('🐔','G_chick2'),
    ('🐍','G_snake'),
    ('🐢','G_turtle'),
    ('🐛','G_caterpillar '),
    ('🐝','G_bee'),
    ('🐜','G_ant'),
    ('🐞','G_ladybug'),
    ('🐌','G_snail'),
    ('🐙','G_octopus'),
    ('🐚','G_shell'),
    ('🐠','G_fish1'),
    ('🐟','G_fish2'),
    ('🐬','G_dolphin'),
    ('🐳','G_whale1'),
    ('🐋','H_whale1'),
    ('🐄','H_cow'),
    ('🐏','H_sheep'),
    ('🐀','H_mouse'),
    ('🐃','H_ox'),
    ('🐅','H_tiger'),
    ('🐇','H_rabbit'),
    ('🐉','H_dragon'),
    ('🐎','H_horse'),
    ('🐐','H_goat'),
    ('🐓','H_chicken'),
    ('🐕','H_dog'),
    ('🐖','H_pig'),
    ('🐁','H_mouse2'),
    ('🐂','H_bull'),
    ('🐲','H_dragon2'),
    ('🐡','H_puffer'),
    ('🐊','H_alligator'),
    ('🐫','H_camel1'),
    ('🐪','H_camel2'),
    ('🐆','H_leopard'),
    ('🐈','H_cat'),
    ('🐩','H_poodle'),
    ('🐾','H_paw'),
    ('💐','I_flower1'),
    ('🌸','I_flower2'),
    ('🌷','I_flower3'),
    ('🍀','I_shamrock'),
    ('🌹','I_flower4'),
    ('🌻','I_flower5'),
    ('🌺','I_flower6'),
    ('🍁','I_leaf1'),
    ('🍃','I_leaf2'),
    ('🍂','I_leaf3'),
    ('🌿','I_leaf4'),
    ('🌾','I_leaf5'),
    ('🍄','I_mushroom'),
    ('🌵','I_cactus'),
    ('🌴','I_palm'),
    ('🌲','I_evergreen'),
    ('🌳','I_tree'),
    ('🌰','I_acorn'),
    ('🌱','I_sprout'),
    ('🌼','I_flower7'),
    ('🌐','J_globe1'),
    ('🌞','J_sun1'),
    ('🌝','J_moonface'),
    ('🌚','J_newface'),
    ('🌑','J_moon1'),
    ('🌒','J_moon2'),
    ('🌓','J_moon3'),
    ('🌔','J_moon4'),
    ('🌕','J_moon5'),
    ('🌖','J_moon6'),
    ('🌗','J_moon7'),
    ('🌘','J_moon8'),
    ('🌜','J_moon9'),
    ('🌛','J_moon10'),
    ('🌙','J_moon11'),
    ('🌍','J_globe2'),
    ('🌎','J_globe3'),
    ('🌏','J_globe4'),
    ('🌋','K_volcano'),
    ('🌌','K_stars1'),
    ('🌠','K_stars2'),
    ('⭐️','K_stars3'),
    ('☀️','K_weather1'),
    ('⛅️','K_weather2'),
    ('☁️','K_weather3'),
    ('⚡️','K_weather4'),
    ('☔️','K_weather5'),
    ('❄️','K_weather6'),
    ('⛄️','K_weather7'),
    ('🌀','K_spiral'),
    ('🌁','K_mountain'),
    ('🌈','K_rainbow'),
    ('🌊','K_wave'),
    ('🎍','L_pine'),
    ('💝','L_heartbox'),
    ('🎎','L_asian'),
    ('🎒','L_backpack'),
    ('🎓','L_graduation'),
    ('🎏','L_windsock'),
    ('🎆','L_firework1'),
    ('🎇','L_firework2'),
    ('🎐','L_latern'),
    ('🎑','L_wind'),
    ('🎃','L_pumpkin'),
    ('👻','L_ghost'),
    ('🎅','L_santa'),
    ('🎅🏻','L_santa1'),
    ('🎅🏼','L_santa2'),
    ('🎅🏽','L_santa3'),
    ('🎅🏾','L_santa4'),
    ('🎅🏿','L_santa5'),
    ('🎄','L_xmastree'),
    ('🎁','L_gift'),
    ('🎋','L_bamboo'),
    ('🎉','L_party1'),
    ('🎊','L_party2'),
    ('🎈','L_balloon'),
    ('🎌','L_flags'),
    ('🔮','L_crystalball'),
    ('🎥','L_camera1'),
    ('📷','L_camera2'),
    ('📹','L_camera3'),
    ('📼','L_tape'),
    ('💿','L_cd1'),
    ('📀','L_cd2'),
    ('💽','L_cd3'),
    ('💾','L_disk'),
    ('💻','L_computer'),
    ('📱','L_iphone'),
    ('☎️','L_phone1'),
    ('📞','L_phone2'),
    ('📟','L_pager'),
    ('📠','L_fax'),
    ('📡','L_microwave'),
    ('📺','L_tv'),
    ('📻','L_radio'),
    ('🔊','L_speaker1'),
    ('🔉','L_speaker2'),
    ('🔈','L_speaker3'),
    ('🔇','L_speaker4'),
    ('🔔','L_bell1'),
    ('🔕','L_bell2'),
    ('📢','L_speaker5'),
    ('📣','L_speaker6'),
    ('⏳','L_hourglass1'),
    ('⌛️','L_hourglass2'),
    ('⏰','L_clock1'),
    ('⌚️','L_clock2'),
    ('🔓','L_lock1'),
    ('🔒','L_lock2'),
    ('🔏','L_lock3'),
    ('🔐','L_lock4'),
    ('🔑','L_lock5'),
    ('🔎','L_magnify'),
    ('💡','L_bulb'),
    ('🔦','L_flashlight'),
    ('🔆','L_bright1'),
    ('🔅','L_bright2'),
    ('🔌','L_plug'),
    ('🔋','L_battery'),
    ('🔍','L_magnify2'),
    ('🛁','L_tub1'),
    ('🛀','L_tub2'),
    ('🚿','L_shower'),
    ('🚽','L_toilet'),
    ('🔧','L_wrench'),
    ('🔩','L_bolt'),
    ('🔨','L_hammer'),
    ('🚪','L_door'),
    ('🚬','L_cigarette'),
    ('💣','L_bomb'),
    ('🔫','L_gun'),
    ('🔪','L_knife'),
    ('💊','L_pill'),
    ('💉','L_needle'),
    ('💰','L_money1'),
    ('💴','L_money2'),
    ('💵','L_money3'),
    ('💷','L_money4'),
    ('💶','L_money5'),
    ('💳','L_money6'),
    ('💸','L_money7'),
    ('📲','L_iphone2'),
    ('📧','L_letter1'),
    ('📥','L_letter2'),
    ('📤','L_letter3'),
    ('✉️','L_letter4'),
    ('📩','L_letter5'),
    ('📨','L_letter6'),
    ('📯','L_horn'),
    ('📫','L_letter7'),
    ('📪','L_letter8'),
    ('📬','L_letter9'),
    ('📭','L_letter10'),
    ('📮','L_letter11'),
    ('📦','L_letter12'),
    ('📝','L_office1'),
    ('📄','L_office2'),
    ('📃','L_office3'),
    ('📑','L_office4'),
    ('📊','L_office5'),
    ('📈','L_office6'),
    ('📉','L_office7'),
    ('📜','L_office8'),
    ('📋','L_office9'),
    ('📅','L_office10'),
    ('📆','L_office11'),
    ('📇','L_office12'),
    ('📁','L_office13'),
    ('📂','L_office14'),
    ('✂️','L_office15'),
    ('📌','L_office16'),
    ('📎','L_office17'),
    ('✒️','L_office18'),
    ('✏️','L_office19'),
    ('📏','L_office20'),
    ('📐','L_office21'),
    ('📕','L_book1'),
    ('📗','L_book2'),
    ('📘','L_book3'),
    ('📙','L_book4'),
    ('📓','L_book5'),
    ('📔','L_book6'),
    ('📒','L_book7'),
    ('📚','L_book8'),
    ('📖','L_book9'),
    ('🔖','L_badge'),
    ('📛','L_badge2'),
    ('🔬','L_science1'),
    ('🔭','L_science2'),
    ('📰','L_news'),
    ('🎨','L_art'),
    ('🎬','L_movie'),
    ('🎤','L_mic'),
    ('🎧','L_earphone'),
    ('🎼','L_music1'),
    ('🎵','L_music2'),
    ('🎶','L_music3'),
    ('🎹','L_music4'),
    ('🎻','L_music5'),
    ('🎺','L_music6'),
    ('🎷','L_music7'),
    ('🎸','L_music8'),
    ('👾','L_game1'),
    ('🎮','L_game2'),
    ('🃏','L_game3'),
    ('🎴','L_game4'),
    ('🀄️','L_game5'),
    ('🎲','L_game6'),
    ('🎯','L_game7'),
    ('🏈','L_sport1'),
    ('🏀','L_sport2'),
    ('⚽️','L_sport3'),
    ('⚾️','L_sport4'),
    ('🎾','L_sport5'),
    ('🎱','L_sport6'),
    ('🏉','L_sport7'),
    ('🎳','L_sport8'),
    ('⛳️','L_sport9'),
    ('🚵','L_sport10'),
    ('🚵🏻','L_sport10_1'),
    ('🚵🏼','L_sport10_2'),
    ('🚵🏽','L_sport10_3'),
    ('🚵🏾','L_sport10_4'),
    ('🚵🏿','L_sport10_5'),
    ('🚴','L_sport11'),
    ('🚴🏻','L_sport11_1'),
    ('🚴🏼','L_sport11_2'),
    ('🚴🏽','L_sport11_3'),
    ('🚴🏾','L_sport11_4'),
    ('🚴🏿','L_sport11_5'),
    ('🏁','L_sport12'),
    ('🏇','L_sport13'),
    ('🏇🏻','L_sport13_1'),
    ('🏇🏼','L_sport13_2'),
    ('🏇🏽','L_sport13_3'),
    ('🏇🏾','L_sport13_4'),
    ('🏇🏿','L_sport13_5'),
    ('🏆','L_sport14'),
    ('🎿','L_sport15'),
    ('🏂','L_sport16'),
    ('🏊','L_sport17'),
    ('🏊🏻','L_sport17_1'),
    ('🏊🏼','L_sport17_2'),
    ('🏊🏽','L_sport17_3'),
    ('🏊🏾','L_sport17_4'),
    ('🏊🏿','L_sport17_5'),
    ('🏄','L_sport18'),
    ('🏄🏻','L_sport18_1'),
    ('🏄🏼','L_sport18_2'),
    ('🏄🏽','L_sport18_3'),
    ('🏄🏾','L_sport18_4'),
    ('🏄🏿','L_sport18_5'),
    ('🎣','L_sport19'),
    ('☕️','M_fooddrink1'),
    ('🍵','M_fooddrink2'),
    ('🍶','M_fooddrink3'),
    ('🍼','M_fooddrink4'),
    ('🍺','M_fooddrink5'),
    ('🍻','M_fooddrink6'),
    ('🍸','M_fooddrink7'),
    ('🍹','M_fooddrink8'),
    ('🍷','M_fooddrink9'),
    ('🍴','M_fooddrink10'),
    ('🍕','M_fooddrink11'),
    ('🍔','M_fooddrink12'),
    ('🍟','M_fooddrink13'),
    ('🍗','M_fooddrink14'),
    ('🍖','M_fooddrink15'),
    ('🍝','M_fooddrink16'),
    ('🍛','M_fooddrink17'),
    ('🍤','M_fooddrink18'),
    ('🍱','M_fooddrink19'),
    ('🍣','M_fooddrink20'),
    ('🍥','M_fooddrink21'),
    ('🍙','M_fooddrink22'),
    ('🍘','M_fooddrink23'),
    ('🍚','M_fooddrink24'),
    ('🍜','M_fooddrink25'),
    ('🍲','M_fooddrink26'),
    ('🍢','M_fooddrink27'),
    ('🍡','M_fooddrink28'),
    ('🍳','M_fooddrink29'),
    ('🍞','M_fooddrink30'),
    ('🍩','M_fooddrink31'),
    ('🍮','M_fooddrink32'),
    ('🍦','M_fooddrink33'),
    ('🍨','M_fooddrink34'),
    ('🍧','M_fooddrink35'),
    ('🎂','M_fooddrink36'),
    ('🍰','M_fooddrink37'),
    ('🍪','M_fooddrink38'),
    ('🍫','M_fooddrink39'),
    ('🍬','M_fooddrink40'),
    ('🍭','M_fooddrink41'),
    ('🍯','M_fooddrink42'),
    ('🍎','M_fooddrink43'),
    ('🍏','M_fooddrink44'),
    ('🍊','M_fooddrink45'),
    ('🍋','M_fooddrink46'),


]

def tuple_from_list(list):
    l = []
    for item in list:
        l.append((item,item))
    return l

class RepliedTo(models.Model):
    twitter_id = models.BigIntegerField()

    def __str__(self):
        return self.twitter_id



class Author(models.Model):

    email = models.EmailField(unique=True, choices=tuple_from_list(POSSIBLE_EMAILS))

    handle = models.CharField(max_length=32)

    token = models.CharField(max_length=64, blank=True, null=True)
    secret = models.CharField(max_length=64, blank=True, null=True)

    name = models.CharField(max_length=64)

    text = models.TextField(blank=True, null=True)

    text_model = models.TextField(blank=True,null=True, editable=False)

    avatar = models.ImageField(upload_to='media/avatar', blank=True,null=True)


    interests = models.CharField(max_length=256, blank=True,null=True)


    _api=None

    def __str__(self):
        return self.handle

    @property
    def can_tweet(self):
        return len(self.token) > 0

    @property
    def api(self):
        if self._api is None and self.can_tweet:
            self._api = twitter.Api(
                consumer_key=settings.CONSUMER_KEY,
                consumer_secret=settings.CONSUMER_SECRET,
                access_token_key=self.token,
                access_token_secret=self.secret
            )
        return self._api


    def get_tweet(self):
        emoji = random.choice(EMOJI)
        insult = random.choice(INSULTS)
        return '.@realDonaldTrump get back to work, %s %s' % (insult,emoji[0])